import logging

DOMAIN = "kvm_switch"
DEFAULT_NAME = "KVM Switch"
DEFAULT_HOST = "10.0.0.10"
DEFAULT_PORT = 1110
DEFAULT_OUTPUT_PORTS = 4

# 常量定义
KVM_SWITCH_MIN_PORT = 1
KVM_SWITCH_MAX_PORT = 4
KVM_SWITCH_MIN_INPUT = 1
KVM_SWITCH_MAX_INPUT = 4

# 状态常量
STATUS_INITIALIZING = "initializing"
STATUS_CONNECTED = "connected"
STATUS_DISCONNECTED = "disconnected"
STATUS_ERROR = "error"